//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubNYITDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyAppInfo
    {
        public string CompanyID { get; set; }
        public int AppID { get; set; }
        public string CompanyAppName { get; set; }
        public string CompanyAppDescription { get; set; }
        public string CompanyAppRetinaIconURL { get; set; }
        public string CompanyAppNonRetinaIconURL { get; set; }
        public string IconColor { get; set; }
        public string RetinaSplashScreenURL { get; set; }
        public string NonRetinaSplashScreenURL { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdaedDateTime { get; set; }
    }
}
