//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubNYITDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UIPropertyPropertyCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UIPropertyPropertyCategory()
        {
            this.UIThemePopertyColors = new HashSet<UIThemePopertyColor>();
        }
    
        public int UIPropertyPropertyCategoryID { get; set; }
        public int UIPropertyCategoryID { get; set; }
        public int UIPropertyID { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual UIProperty UIProperty { get; set; }
        public virtual UIPropertyCategory UIPropertyCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UIThemePopertyColor> UIThemePopertyColors { get; set; }
    }
}
