//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubNYITDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UIPropertyCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UIPropertyCategory()
        {
            this.UIControlPropertyCategories = new HashSet<UIControlPropertyCategory>();
            this.UIPropertyCategory1 = new HashSet<UIPropertyCategory>();
            this.UIPropertyPropertyCategories = new HashSet<UIPropertyPropertyCategory>();
        }
    
        public int UIPropertyCategoryID { get; set; }
        public string UIPropertyCategoryName { get; set; }
        public Nullable<int> UIPropertyCategoryParent { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UIControlPropertyCategory> UIControlPropertyCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UIPropertyCategory> UIPropertyCategory1 { get; set; }
        public virtual UIPropertyCategory UIPropertyCategory2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UIPropertyPropertyCategory> UIPropertyPropertyCategories { get; set; }
    }
}
