//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubNYITDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UITheme
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UITheme()
        {
            this.CompanyThemes = new HashSet<CompanyTheme>();
            this.SiteThemes = new HashSet<SiteTheme>();
        }
    
        public long UIThemeID { get; set; }
        public string UIThemeName { get; set; }
        public int Version { get; set; }
        public string RetinaBackgroundImageURL { get; set; }
        public string NonRetinaBackgroundImageURL { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyTheme> CompanyThemes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiteTheme> SiteThemes { get; set; }
    }
}
